export const PROJECT_LIST_REQUEST = "PROJECT_LIST_REQUEST"
export const PROJECT_LIST_SUCCESS = "PROJECT_LIST_SUCCESS"
export const PROJECT_LIST_FAIL = "PROJECT_LIST_FAIL"

export const PROJECT_DETAILS_REQUEST = "PROJECT_DETAILS_REQUEST"
export const PROJECT_DETAILS_SUCCESS = "PROJECT_DETAILS_SUCCESS"
export const PROJECT_DETAILS_FAIL = "PROJECT_DETAILS_FAIL"

export const ADD_CONTRIBUTOR_REQUEST = "ADD_CONTRIBUTOR_REQUEST"
export const ADD_CONTRIBUTOR_SUCCESS = "ADD_CONTRIBUTOR_SUCCESS"
export const ADD_CONTRIBUTOR_FAIL = "ADD_CONTRIBUTOR_FAIL"
export const ADD_CONTRIBUTOR_RESET = "ADD_CONTRIBUTOR_RESET"

export const PROJECT_CREATE_REQUEST = "PROJECT_CREATE_REQUEST"
export const PROJECT_CREATE_SUCCESS = "PROJECT_CREATE_SUCCESS"
export const PROJECT_CREATE_FAIL = "PROJECT_CREATE_FAIL"
export const PROJECT_CREATE_RESET = "PROJECT_CREATE_RESET"

export const PROJECT_EDIT_REQUEST = "PROJECT_EDIT_REQUEST"
export const PROJECT_EDIT_SUCCESS = "PROJECT_EDIT_SUCCESS"
export const PROJECT_EDIT_FAIL = "PROJECT_EDIT_FAIL"
export const PROJECT_EDIT_RESET = "PROJECT_EDIT_RESET"

export const PROJECT_DELETE_REQUEST = "PROJECT_DELETE_REQUEST"
export const PROJECT_DELETE_SUCCESS = "PROJECT_DELETE_SUCCESS"
export const PROJECT_DELETE_FAIL = "PROJECT_DELETE_FAIL"
export const PROJECT_DELETE_RESET = "PROJECT_DELETE_RESET"