export const TASK_LIST_REQUEST = "TASK_LIST_REQUEST"
export const TASK_LIST_SUCCESS = "TASK_LIST_SUCCESS"
export const TASK_LIST_FAIL = "TASK_LIST_FAIL"

export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST"
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS"
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL"