export const TASK_LIST_REQUEST = "TASK_LIST_REQUEST"
export const TASK_LIST_SUCCESS = "TASK_LIST_SUCCESS"
export const TASK_LIST_FAIL = "TASK_LIST_FAIL"

export const TASK_DETAIL_REQUEST = "TASK_DETAIL_REQUEST"
export const TASK_DETAIL_SUCCESS = "TASK_DETAIL_SUCCESS"
export const TASK_DETAIL_FAIL = "TASK_DETAIL_FAIL"

export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST"
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS"
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL"
export const CREATE_TASK_RESET = "CREATE_TASK_RESET"

export const ASSIGN_TASK_REQUEST = "ASSIGN_TASK_REQUEST"
export const ASSIGN_TASK_SUCCESS = "ASSIGN_TASK_SUCCESS"
export const ASSIGN_TASK_FAIL = "ASSIGN_TASK_FAIL"

export const UPDATE_TASK_TO_IN_PROGRESS_REQUEST = "UPDATE_TASK_TO_IN_PROGRESS_REQUEST"
export const UPDATE_TASK_TO_IN_PROGRESS_SUCCESS = "UPDATE_TASK_TO_IN_PROGRESS_SUCCESS"
export const UPDATE_TASK_TO_IN_PROGRESS_FAIL = "UPDATE_TASK_TO_IN_PROGRESS_FAIL"

export const UPDATE_TASK_TO_DONE_REQUEST = "UPDATE_TASK_TO_DONE_REQUEST"
export const UPDATE_TASK_TO_DONE_SUCCESS = "UPDATE_TASK_TO_DONE_SUCCESS"
export const UPDATE_TASK_TO_DONE_FAIL = "UPDATE_TASK_TO_DONE_FAIL"

export const EDIT_TASK_REQUEST = "EDIT_TASK_REQUEST"
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS"
export const EDIT_TASK_FAIL = "EDIT_TASK_FAIL"
export const EDIT_TASK_RESET = "EDIT_TASK_RESET"

export const CREATE_TASK_MESSAGE_REQUEST = "CREATE_TASK_MESSAGE_REQUEST"
export const CREATE_TASK_MESSAGE_SUCCESS = "CREATE_TASK_MESSAGE_SUCCESS"
export const CREATE_TASK_MESSAGE_FAIL = "CREATE_TASK_MESSAGE_FAIL"

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST"
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS"
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL"