export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST"
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS"
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL"

export const USER_PROFILE_EDIT_REQUEST = "USER_PROFILE_EDIT_REQUEST"
export const USER_PROFILE_EDIT_SUCCESS = "USER_PROFILE_EDIT_SUCCESS"
export const USER_PROFILE_EDIT_FAIL = "USER_PROFILE_EDIT_FAIL"

export const USER_LIST_REQUEST = "USER_LIST_REQUEST"
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS"
export const USER_LIST_FAIL = "USER_LIST_FAIL"

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"

export const USER_EDIT_REQUEST = "USER_EDIT_REQUEST"
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS"
export const USER_EDIT_FAIL = "USER_EDIT_FAIL"
export const USER_EDIT_RESET = "USER_EDIT_RESET"

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST"
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS"
export const USER_DELETE_FAIL = "USER_DELETE_FAIL"

export const GET_CONTRIBUTORS_REQUEST = "GET_CONTRIBUTORS_REQUEST"
export const GET_CONTRIBUTORS_SUCCESS = "GET_CONTRIBUTORS_SUCCESS"
export const GET_CONTRIBUTORS_FAIL = "GET_CONTRIBUTORS_FAIL"
