# Generated by Django 4.1.3 on 2022-11-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='urgency',
            field=models.CharField(default='very urgent', max_length=250),
            preserve_default=False,
        ),
    ]
